spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true

server:
  port: 8380

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8380/eureka/

---
spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true

server:
  port: 8380
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/

---
spring:
  profiles: docker
server:
  port: 8380
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
eureka:
  instance:
    hostname: discovery
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:8380/eureka/