spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  boot.admin.url: http://localhost:8384
  zipkin:
    baseUrl: http://localhost:8383
  sleuth:
    sampler:
      percentage: 1
  datasource:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import_products.sql
  jpa:
    show_sql: true
    generate-ddl: false
    database: H2
    hibernate:
      ddl-auto: none

server:
  port: 8386

management.security.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8380/eureka/

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: cloud
  zipkin:
    baseUrl: http://zipkin-22.cfapps.io/
  sleuth:
    sampler:
      percentage: 1
  datasource:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import_products.sql
  jpa:
    show_sql: false
    generate-ddl: true
    database: H2
    hibernate:
      ddl-auto: none

server:
  port: 8386

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
  instance:
    hostname: movie-77.cfapps.io
    nonSecurePort: 80

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://192.168.99.100:8383
  sleuth:
    sampler:
      percentage: 1
  datasource:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import_products.sql
  jpa:
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none

server:
  port: 8386

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8380/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true