insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Mouse', 'Mouse', 'Apple', 25, 20.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Keyboard', 'Keyboard', 'Apple', 25, 40.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Printer', 'Printer', 'Apple', 20, 520.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Ultra Display', 'Display', 'Apple', 25, 220.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('MacBook Pro', 'Laptop', 'Apple', 40, 1320.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('iMac', 'Desktop', 'Apple', 40, 1220.00, 3);

insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Mouse', 'Mouse', 'Sony', 25, 18.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Keyboard', 'Keyboard', 'Sony', 25, 38.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Printer', 'Printer', 'Sony', 25, 460.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Sony Display', 'Display', 'Sony', 25, 210.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Sony Wio', 'Laptop', 'Sony', 50, 920.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Sony Desktops', 'Desktop', 'Sony', 50, 1110.00, 3);

insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Mouse', 'Mouse', 'Dell', 25, 20.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Keyboard', 'Keyboard', 'Dell', 25, 35.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Printer', 'Printer', 'Dell', 15, 450.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Dell Clear Display', 'Display', 'Dell', 25, 220.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Dell Notebook', 'Laptop', 'Dell', 45, 860.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Dell Station', 'Desktop', 'Dell', 45, 1020.00, 3);

insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Mouse', 'Mouse', 'Lenovo', 25, 19.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Keyboard', 'Keyboard', 'Lenovo', 25, 39.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Printer', 'Printer', 'Lenovo', 15, 420.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('HD Display', 'Display', 'Lenovo', 25, 220.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('ThinkPad', 'Laptop', 'Lenovo', 25, 1220.00, 3);
insert into PRODUCT_CATALOGUE (PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_MAKER, PRODUCT_QUANTITY, PRODUCT_PRICE, VERSION) values ('Lenovo Desk', 'Desktop', 'Lenovo', 25, 980.00, 3);