drop table if exists `PRODUCT_CATALOGUE`;
CREATE TABLE `PRODUCT_CATALOGUE` (
  `PRODUCT_ID` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(100),
  `PRODUCT_TYPE` VARCHAR(100),
  `PRODUCT_MAKER` VARCHAR(100),
  `PRODUCT_QUANTITY` INT(3),
  `PRODUCT_PRICE` DECIMAL(6,2),
  `CREATED_BY` VARCHAR(100),
  `CREATED_DATE` DATE,
  `UPDATED_BY` VARCHAR(100),
  `UPDATED_DATE` DATE,
  `VERSION` INT(3),
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
