spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  boot.admin.url: http://localhost:8384
  zipkin:
    baseUrl: http://localhost:8383
  sleuth:
    sampler:
      percentage: 1
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: gateway
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8380/eureka/
ribbon:
  eureka:
    enabled: true
      
sidecar:
  port: 8000
  
management.security.enabled: false

---

spring:
  profiles: cloud
  boot.admin.url: http://admin-33.cfapps.io/
  zipkin:
    baseUrl: http://zipkin-22.cfapps.io/
  sleuth:
    sampler:
      percentage: 1
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: gateway-77.cfapps.io
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
      
sidecar:
  port: 8000

---

spring:
  profiles: docker
  boot.admin.url: http://192.168.99.100:8384
  zipkin:
    baseUrl: http://192.168.99.100:8383
  sleuth:
    sampler:
      percentage: 1
server:
  port: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8380/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
    
sidecar:
  port: 8000